apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-bucket-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: cs-fuse-bucket #does not need to refer to an existing StorageClass object
  mountOptions:
    - implicit-dirs
    - uid=1001
    - gid=3003
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: {{ .Values.GCStorage.bucket_name }}
    readOnly: true #optional