apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  podManagementPolicy: OrderedReady
  replicas: 1
  serviceName: db-headless
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: kartoza/postgis:16-3.4
          name: db
          env:
            - name: ALLOW_IP_RANGE
              value: "0.0.0.0/0"
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
            - name: FORCE_SSL
              value: "TRUE"
            - name: POSTGRES_PASS
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
          ports:
          - containerPort: 5432
            name: {{ .Values.postgres.port }}
            protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/postgresql
            name: dbdata
      restartPolicy: Always
      volumes:
      - name: dbdata
        persistentVolumeClaim:
            claimName: dbdata
  volumeClaimTemplates:
    - metadata:
        name: dbdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 8Gi
