apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db-headless
spec:
  clusterIP: None
  ports:
    - name: db
      port: {{ .Values.postgres.port }}
      targetPort: 5432
  selector:
    app: db