apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserver-cluster-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: filestore-sc
  resources:
    requests:
      storage: 1Ti