apiVersion: v1
kind: Service
metadata:
  labels:
    app: master
  name: master
spec:
  ports:
    - name: geomaster-port
      port: 8081
      targetPort: 8080
    - name: broker-port
      port: 61661
      targetPort: 61661
  selector:
    app: master
