apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "geoserver.fullname" . }}
  labels:
    app: {{ template "geoserver.fullname" . }}
    chart: {{ template "geoserver.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.container.master.replicas }}
  selector:
    matchLabels:
      app: {{ template "geoserver.fullname" . }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      name: {{ template "geoserver.fullname" . }}
      labels:
        app: {{ template "geoserver.fullname" . }}
        chart: {{ template "geoserver.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        {{- with .Values.podLabels }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- (tpl . $) | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ template "geoserver.fullname" . }}
          image: {{ template "geoserver.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            - name: BROKER_URL
              value: tcp://0.0.0.0:61661
            - name: HOST
              value: db-headless
            - name: CLUSTERING
              value: "True"
            - name: CLUSTER_DURABILITY
              value: "false"
            - name: DB_BACKEND
              value: POSTGRES
            - name: READONLY
              value: disabled
            - name: SSL_MODE
              value: allow
            - name: TOGGLE_MASTER
              value: "true"
            - name: TOGGLE_SLAVE
              value: "true"
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
            - name: POSTGRES_PASS
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            {{- if .Values.enableJSONP }}
            - name: ENABLE_JSONP
              value: {{ .Values.enableJSONP | quote }}
            {{- end }}
            {{- if .Values.geowebcacheCacheDir }}
            - name: GEOWEBCACHE_CACHE_DIR
              value: {{ .Values.geowebcacheCacheDir | quote }}
            {{- end }}
            - name: GEOSERVER_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "geoserver.secretName" . }}
                  key: geoserver-user
            - name: GEOSERVER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "geoserver.secretName" . }}
                  key: geoserver-password
            {{- with .Values.extraPodEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 8080
              protocol: TCP
              name: geomaster-port
            - containerPort: 61661
              protocol: TCP
              name: broker-port
          {{- if .Values.probe }}
            {{- with .Values.probe }}
            {{- tpl . $ | nindent 10 }}
            {{- end }}
          {{- else }}
          lifecycle:
            preStop:
              exec:
                command: [ "/usr/local/tomcat/bin/catalina.sh stop && sleep 30" ]
          startupProbe:
            httpGet:
              path: /geoserver
              port: http-geoserver
            failureThreshold: 60
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /geoserver
              port: http-geoserver
              scheme: HTTP
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /geoserver
              port: http-geoserver
              scheme: HTTP
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
          {{- end }}
          volumeMounts:
            - mountPath: /opt/geoserver/data_dir
              name: geoserver-cluster-data
            - mountPath: /opt/geoserver/gwc
              name: geoserver-gwc-data
            {{- with .Values.extraVolumeMounts }}
            {{- (tpl . $) | nindent 12 }}
            {{- end }}
      {{- with .Values.extraPodSpec }}
      {{- tpl . $ | nindent 6 }}
      {{- end }}
      restartPolicy: Always
      volumes:
        {{- with .Values.extraVolume }}
        {{- (tpl . $) | nindent 8 }}
        {{- end }}
        - name: geoserver-cluster-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.geoserverDataDir.existingClaim }}
        - name: geoserver-gwc-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.geowebcacheCacheDir.existingClaim }}