apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClassFS.name }}
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: {{ .Values.storageClassFS.volumeBindingMode }}
allowVolumeExpansion: true
reclaimPolicy: {{ .Values.storageClassFS.reclaimPolicy }}
parameters:
  tier: {{ .Values.storageClassFS.parameters.tier }}
  network: {{ .Values.storageClassFS.parameters.network }}