
# PVC for GCS integration
{{- if .Values.GCStorage.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.extraVolume.persistentVolumeClaim.claimName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: {{ .Values.extraVolume.name }}
  storageClassName: gcs-fuse-bucket
...
{{- end }}
