
# PVC for GCS integration
{{- if .Values.GCStorage.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-xcube-bucket-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: gcs-xcube-bucket-pv
  storageClassName: gcs-fuse-bucket
...
{{- end }}
