apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "xcube.fullname" . }}
  labels:
    app: {{ template "xcube.fullname" . }}
    chart: {{ template "xcube.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.container.replicas }}
  selector:
    matchLabels:
      app: {{ template "xcube.fullname" . }}
      release: {{ .Release.Name | quote }}
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{ template "xcube.fullname" . }}
      labels:
        app: {{ template "xcube.fullname" . }}
        chart: {{ template "xcube.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        {{- with .Values.podLabels }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- (tpl . $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.GCStorage.enabled }}
      serviceAccountName: {{ .Values.GCStorage.serviceAccountName }}
      {{- end }}
      imagePullSecrets:
        - name: docker-pull-secret
      containers:
        - image: {{ .Values.container.image }}
          name: xcube
          imagePullPolicy: {{ .Values.container.pullPolicy }}
          {{- if .Values.container.command }}
          command: {{ .Values.container.command }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: {{ .Values.configmap.mountPath }}
              name: {{ .Values.configmap.name }}
            {{- with .Values.extraVolumeMounts }}
            {{- (tpl . $) | nindent 12 }}
            {{- end }}
      restartPolicy: Always
      volumes:
        - name: {{ .Values.configmap.name }}
          configMap:
            name: xcube-configmap
        {{- with .Values.extraVolume }}
        {{- (tpl . $) | nindent 8 }}
        {{- end }}
status: {}
