DatasetAttribution:
  - "© by GMATICS srl and ESA"

#DatasetChunkCacheSize: 100M

## You may want to specify a location of your server resources.
#base_dir: s3://<bucket>/<path-to-your>/<resources>/

## You may want to specify a remote location of your viewer resources.
#Viewer:
#  Configuration:
#    Path: s3://<bucket>/<path-to-your-viewer>/<resources>
DataStores:

  # This section needs to be kept, because it is part of xcube server documentation using DataStores.
  - Identifier: cosenza
    StoreId: s3
    StoreParams:
      root: eos4lpa-cubes-bucket/comune_cosenza
      max_depth: 9
      storage_options:
        anon: false
        #client_kwargs:
        key: AKIATCNUVNJ6CGCOSUTA
        secret: 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

        #endpoint_url: https://s3.eu-west-3.amazonaws.com
    Datasets:
      - Path: "*.zarr"
        Style: "default"