name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run Helm package
        run: |
          helm package charts/xcube/v0.1.1

      - name: Release Helm charts
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_dir: charts
          token: "${{ secrets.API_GITHUB_TOKEN }}"

