apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: xcube
  name: xcube
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: xcube
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: xcube
    spec:
      imagePullSecrets:
        - name: docker-pull-secret
      containers:
        - image: gmaticseu/xcube:SYS-92
          name: xcube
          command: ["/bin/sh", "-c", "sleep 600"]

          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/config
              name: xcube-configmap-volume
      restartPolicy: Always
      volumes:
        - name: xcube-configmap-volume
          configMap:
            name: xcube-configmap
status: {}
